### PR TITLE
[SB-24521] Upgrading node version

### PR DESCRIPTION
**Pull request by pritamps**
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

### Type of change

Please choose appropriate options.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

### How Has This Been Tested?

Ran QuML player E2E locally and verified that everything is working

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by HarishGangula** [comment]
@pritamps  Please provide sunbird Jira id inside the title of the PR for this change.

**Comment by pritamps** [comment]
Hi @HarishGangula , I don't think I have access to create JIRAs. Could you please provide my Avanti ID (pritam@avantifellows.org) with this access, so that I can create JIRAs?

**Comment by HarishGangula** [comment]
@surendrasinghs  can you help @pritamps  with the JIRA story for this PR

**Comment by surendrasinghs** [comment]
@pritamps Please use https://project-sunbird.atlassian.net/browse/SB-24521

**Comment by surendrasinghs** [comment]
@pritamps The person managing access if out of office since last week. We will get the access done soon as he's back.

**Comment by pritamps** [comment]
> @pritamps Please provide sunbird Jira id inside the title of the PR for this change.

@HarishGangula this is done. Thanks @surendrasinghs !

**Pull request merged**
